### ISSUE TITLE
Bosch GLM bluetooth proticol

### ISSUE THREAD

**Issue by madeleinefrancis** [lz1asl/CaveSurvey#142]
Hello,
I'm currently looking for Bosch bluetooth commands for a project but it seems that your files which may have contained those have been deleted? If you have any leads as to where to get a list of those commands I would be very appreciative as your app seems to have used that at least at some point in time.

Thank you :)

**Comment by lz1asl** [comment]
Hey,

I am not allowed to publish the Bosch binaries as they are proprietary and I have signed non disclosure agreement. That's why there is a patch file so you can compile the project without it.
But you can get your own copy of the library. Have a look at the GLM devices wiki and write to the Bosch app support email listed there. Once you sign the papers and get the library you will have no issues reading data from these devices.

All the best

**Comment by madeleinefrancis** [comment]
Thank for your reply it helps a lot in my search!
